name: Scrape and Notify

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      URL: 'https://airrsv.net/muramotokaiji/calendar/menuDetail/?schdlId=T003EDD66B'
      GREP_PATTERN: 'このサービスは'
      MESSAGE: '今予約いけそう\nhttps://airrsv.net/muramotokaiji/calendar/menuDetail/?schdlId=T003EDD66B'
      LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Run notifier
        run: bash command.sh
